# Generated by Django 4.1.1 on 2022-09-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.IntegerField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=200)),
                ('Med_rec_no', models.IntegerField(max_length=200)),
                ('spec', models.TextField(max_length=200)),
                ('hosp_name', models.TextField(max_length=200)),
                ('exp', models.TextField(max_length=200)),
            ],
        ),
    ]
