# Generated by Django 4.1.1 on 2022-09-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_doctor_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hosp_name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.TextField(max_length=200),
        ),
    ]
